project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from ads.api import MyAdsAPI, AdViewSet
from ads.views import HomeView, AdDetailView, AdFormView, MyAdsView
from users.api import UserViewSet
from users.views import LogoutView, LoginView


router = DefaultRouter()
router.register('ads', AdViewSet)
router.register('users', UserViewSet, base_name='users')


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),
    path('mis-anuncios', MyAdsView.as_view(), name='my-ads'),
    path('anuncio/nuevo', AdFormView.as_view(), name='ad-form'),
    path('anuncio/<int:pk>', AdDetailView.as_view(), name='ad-detail'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),

    # API URLs
    path('api/v1/', include(router.urls)),
    path('api/v1/ads/mine/', MyAdsAPI.as_view(), name='api-ads-mine')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ads/models.py
from django.contrib.auth.models import User
from django.db import models


class Ad(models.Model):

    BUY = 'BUY'
    SELL = 'SEL'
    TYPES = (
        (BUY, 'Buying'),
        (SELL, 'Selling')
    )

    PENDING = 'PEN'
    APPROVED = 'APR'
    FINISHED = 'FIN'
    STATUSES = (
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (FINISHED, 'Finished')
    )

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    description = models.TextField(null=True, blank=True)  # null=True, blank=True => campo opcional
    price = models.FloatField()
    image = models.FileField(null=True)  # null=True => campo opcional
    send_choice = models.BooleanField(default=False)
    type = models.CharField(max_length=3, choices=TYPES, default=SELL)
    status = models.CharField(max_length=3, choices=STATUSES, default=PENDING)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        """
        Define cómo se representa un Ad como una string
        """
        return '{0} ({1} €)'.format(self.name, self.price)

users/models.py
from django.db import models

# Create your models here.

ads/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from ads.models import Ad


class AdForm(ModelForm):

    class Meta:
        model = Ad
        fields = '__all__'
        exclude = ['owner', 'status']

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image is not None and 'image' not in image.content_type:
            raise ValidationError('El archivo no es una imagen válida')
        return image

    def clean(self):
        super().clean()  # al llamar al método clean de la superclase garantizamos la validacion de los campos del modelo
        send_choice = self.cleaned_data.get('send_choice', False)
        type = self.cleaned_data.get('type')
        if type == Ad.BUY and send_choice:
            raise ValidationError('Los anuncios de compra no pueden llevar envío.')

users/forms.py
from django import forms


class LoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

ads/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView

from ads.forms import AdForm
from ads.models import Ad


class HomeView(ListView):

    model = Ad
    template_name = 'ads/list.html'

    def get_queryset(self):
        result = super().get_queryset()
        return result.filter(status=Ad.PENDING).order_by('-created_on')[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Django Pop'
        context['claim'] = 'Una plataforma de anuncios hecha con Django'
        return context


@method_decorator(login_required, name='dispatch')
class MyAdsView(ListView):

    model = Ad
    template_name = 'ads/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mis anuncios'
        context['claim'] = 'Este listado es de los anuncios que has creado tú'
        return context


class AdDetailView(View):

    def get(self, request, pk):
        """
        Muestra el detalle de un anuncio
        :param request: objeto HttpRequest
        :param pk: identificador del anuncio
        :return: HttpResponse con la respuesta
        """
        # recuperar de la base de datos el anuncio que me piden
        try:
            ad = Ad.objects.select_related().get(pk=pk)
        except Ad.DoesNotExist:
            # si no existe el anuncio, devolvemos un 404
            return HttpResponse('No existe el anuncio que buscas', status=404)

        # si existe el anuncio, creamos el contexto
        context = {'ad': ad}

        # devolver la respuesta utilizando una plantilla
        return render(request, 'ads/detail.html', context)


@method_decorator(login_required, name='dispatch')
class AdFormView(View):

    def get(self, request):
        """
        Muestra el formulario para crear un anuncio
        :param request: objeto HttpRequest
        :return: HttpResponse con la respuesta
        """
        form = AdForm()
        context = {'form': form}
        return render(request, 'ads/form.html', context)

    def post(self, request):
        """
        Procesa el formulario para crear un anuncio
        :param request: objeto HttpRequest
        :return: HttpResponse con la respuesta
        """
        ad = Ad()
        ad.owner = request.user
        form = AdForm(request.POST, request.FILES, instance=ad)
        if form.is_valid():
            # creamos el anuncio
            ad = form.save()
            # limpiar el formulario
            form = AdForm()
            # Devolvemos un mensaje de OK
            messages.success(request, 'Anuncio creado correctamente')
        context = {'form': form}
        return render(request, 'ads/form.html', context)

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from django.contrib.auth import login as django_login, logout as django_logout
from django.views import View

from users.forms import LoginForm


class LoginView(View):

    def get(self, request):
        """
        Muestra el formulario de login
        :param request: objeto HttpRequest
        :return: objeto HttpResponse con el formulario renderizado
        """
        form = LoginForm()
        context = {'form': form}
        return render(request, 'users/login.html', context)

    def post(self, request):
        """
        Procesa el login de un usuario
        :param request: objeto HttpRequest
        :return: objeto HttpResponse con el formulario renderizado
        """
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # comprobamos si las credenciales son correctas
            user = authenticate(username=username, password=password)
            if user is None:
                messages.error(request, 'Usuario o contraseña incorrecto')
            else:
                # iniciamos la sesión del usuario (hacemos login del usuario)
                django_login(request, user)
                url = request.GET.get('next', 'home')
                return redirect(url)

        context = {'form': form}
        return render(request, 'users/login.html', context)


class LogoutView(View):

    def get(self, request):
        """
        Hace logout de un usuario y le redirige al login
        :param request: objeto HttpRequest
        :return: objeto HttpResponse de redirección al login
        """
        django_logout(request)
        return redirect('login')

ads/templates/ads/detail.html
{% extends "base.html" %}

{% block title %} {{ ad.name }} {% endblock %}

{% block body %}
    <h1>{{ ad.name }}</h1>
    <h2>{{ ad.price }} €</h2>
    <img src="{{ ad.image.url }}" alt="{{ ad.name }}" title="{{ ad.name }}">
    <p>{{ ad.description }}</p>
    <ul>
        <li>
            <strong>Propietario:</strong> {{ ad.owner.first_name }} {{ ad.owner.last_name }}
        </li>
        <li>
            <strong>Tipo:</strong> {{ ad.get_type_display }}
        </li>
        <li>
            <strong>Estado:</strong> {{ ad.get_status_display }}
        </li>
    </ul>
{% endblock %}

ads/templates/ads/form.html
{% extends "base.html" %}

{% block title %} Nuevo anuncio {% endblock %}

{% block body %}

<h1>Nuevo anuncio</h1>

{% include 'includes/messages.html' %}

<form method="post" enctype="multipart/form-data" novalidate>

    {% csrf_token %}

    {{ form.as_p }}

    <button>Crear anuncio</button>

</form>

{% endblock %}

ads/templates/ads/list.html
{% extends "base.html" %}

{% block body %}
    <h1>{{ title }}</h1>

    <p>{{ claim }}</p>

    {% for ad in object_list %}
        <a href="{% url 'ad-detail' ad.pk %}">
            <div class="ad">
                <img src="{{ ad.image.url }}" alt="{{ ad.name }}" title="{{ ad.name }}">
                <p>
                    {{ ad.name }} <strong>{{ ad.price}} €</strong>
                </p>
            </div>
        </a>
    {% endfor %}
{% endblock %}

ads/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} DjangoPop {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <style>
        .ad { float: left; width: 200px; }
        .ad img { width: 200px; }
    </style>
</head>
<body>
    <div class="container">
        <nav>
            <a href="{% url 'home' %}">Home</a>
            |
            {% if user.is_authenticated %}
                <a href="{% url 'my-ads' %}">Mis anuncios</a>
                |
                <a href="{% url 'ad-form' %}">Nuevo anuncio</a>
                |
                Hola {{ user.first_name }},
                <a href="{% url 'logout' %}">logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
            <hr>
        </nav>
        {% block body %}{% endblock %}
    </div>
</body>
</html>

ads/templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        {% if 'error' in message.tags %}
            <div style="color:red">{{ message }}</div>
        {% elif 'success' in message.tags %}
            <div style="color:green">{{ message }}</div>
        {% elif 'warning' in message.tags %}
            <div style="color:orange">{{ message }}</div>
        {% elif 'info' in message.tags %}
            <div style="color:dodgerblue">{{ message }}</div>
        {% else %}
            <div>{{ message }}</div>
        {% endif %}
    {% endfor %}
{% endif %}

users/templates/users/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block body %}

<h1>Login</h1>

{% include 'includes/messages.html' %}

<form method="post" novalidate>
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Login</button>

</form>

{% endblock %}